"""Initializing

Revision ID: 29eb105100f4
Revises: ea69736379a1
Create Date: 2026-09-13 02:36:12.241953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29eb105100f4'
down_revision: Union[str, Sequence[str], None] = 'ea69736379a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followups_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_patient_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_screening_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_table('Database_Model')
    op.drop_index(op.f('ix_priority_escalations_id'), table_name='priority_escalations')
    op.drop_index(op.f('ix_priority_escalations_screening_id'), table_name='priority_escalations')
    op.drop_table('priority_escalations')
    op.drop_table('table_name')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_screenings_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_patient_id'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_table('Database__Model')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_symptom_extractions_id'), table_name='symptom_extractions')
    op.drop_index(op.f('ix_symptom_extractions_patient_id'), table_name='symptom_extractions')
    op.drop_table('symptom_extractions')
    op.drop_index(op.f('ix_FastAPIModel_id'), table_name='FastAPIModel')
    op.drop_table('FastAPIModel')
    op.drop_table('Database___Model')
    op.drop_table('Database_Argha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Database_Argha',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Database_Argha_pkey')),
    sa.UniqueConstraint('answer', name=op.f('Database_Argha_answer_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('Database___Model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Database_Argha.id'], name=op.f('Database___Model_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Database___Model_pkey')),
    sa.UniqueConstraint('email', name=op.f('Database___Model_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('Database___Model_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('FastAPIModel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phonenumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('emergency_contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('FastAPIModel_pkey'))
    )
    op.create_index(op.f('ix_FastAPIModel_id'), 'FastAPIModel', ['id'], unique=False)
    op.create_table('symptom_extractions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('screening_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('symptom_extractions_pkey'))
    )
    op.create_index(op.f('ix_symptom_extractions_patient_id'), 'symptom_extractions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_symptom_extractions_id'), 'symptom_extractions', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Phone_Number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Preferred_Language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Village', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('District', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('State', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Pincode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Emergency_Contact_Name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Emergency_Contact_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('patients_pkey'))
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('Database__Model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Database_Argha.id'], name=op.f('Database__Model_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Database__Model_pkey')),
    sa.UniqueConstraint('email', name=op.f('Database__Model_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('Database__Model_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('screenings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symptoms', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('breathing_difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emergency_warning_sign', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('symptoms_worsening', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('screenings_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('screenings_pkey'))
    )
    op.create_index(op.f('ix_screenings_patient_id'), 'screenings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_screenings_id'), 'screenings', ['id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('screening_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('referral_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('urgency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('referrals_patient_id_fkey')),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('referrals_screening_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('referrals_pkey'))
    )
    op.create_table('table_name',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('table_name_pkey')),
    sa.UniqueConstraint('email', name=op.f('table_name_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('table_name_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('priority_escalations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('screening_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('old_priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('new_priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('priority_escalations_screening_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('priority_escalations_pkey'))
    )
    op.create_index(op.f('ix_priority_escalations_screening_id'), 'priority_escalations', ['screening_id'], unique=False)
    op.create_index(op.f('ix_priority_escalations_id'), 'priority_escalations', ['id'], unique=False)
    op.create_table('Database_Model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Database_Model_pkey')),
    sa.UniqueConstraint('email', name=op.f('Database_Model_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('Database_Model_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('followups',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('screening_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduled_after_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symptoms_improved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('symptoms_worsened', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('followup_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('followups_patient_id_fkey')),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('followups_screening_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('followups_pkey'))
    )
    op.create_index(op.f('ix_followups_screening_id'), 'followups', ['screening_id'], unique=False)
    op.create_index(op.f('ix_followups_patient_id'), 'followups', ['patient_id'], unique=False)
    op.create_index(op.f('ix_followups_id'), 'followups', ['id'], unique=False)
    # ### end Alembic commands ###
